version: '3'
services:
  db:
    image: postgres:15.2
    environment:
      POSTGRES_DB: "auth"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:3
    ports:
        # If you're also running a Redis instance on host, map 6379 in container to a different port on host,
        # such as 6380. Otherwise can use "6379:6379" here. This is useful for connecting a Redis client from
        # host machine to container.
        - "6380:6379"
  app:
    build: .
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_path:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - "db"
      - "redis"
volumes:
  bundle_path:
